name        : jml-java-6          # name of the package
version     : 1.6-2               # version of the package
kind        : spec                # one of tool or spec(s)
description : JML Specifications for the Java Language, Version 6.
extends     : jml-java-5              
author:
  - name: John L. Singleton
    email: jsinglet@gmail.com


